### ISSUE TITLE
How to extend the linear actuator prior to assembly?

### ISSUE THREAD

**Issue by sgbaird** [ac-rad/digital-pipette#1]
It shipped in the fully retracted state, and it seems to be geared down at a high enough ratio that I can't pull it out by hand. Do you suggest running the code before assembling the hardware? Something else?

**Comment by sgbaird** [comment]
Response from @n-yoshikawa:
> I usually run the code before assembly

**Comment by n-yoshikawa** [comment]
I update the documentation to clarify this. Thank you for pointing it out!
